'use strict';window.DOMHandler=class{constructor(d,f){this._iRuntime=d;this._componentId=f;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(d,f,h,l){this._iRuntime.PostToRuntimeComponent(this._componentId,d,f,h,l)}PostToRuntimeAsync(d,f,h,l){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,d,f,h,l)}_PostToRuntimeMaybeSync(d,f,h){this._iRuntime.UsesWorker()?this.PostToRuntime(d,f,h):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:d,dispatchOpts:h||null,data:f,responseId:null})}AddRuntimeMessageHandler(d,f){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,d,f)}AddRuntimeMessageHandlers(d){for(const [f,h]of d)this.AddRuntimeMessageHandler(f,h)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(d,f){this._callback=d;this._interval=f;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(d){this._canRunImmediate=!!d}Call(){if(-1===this._timerId){var d=Date.now(),f=d-this._lastCallTime,h=this._interval;f>=h&&this._canRunImmediate?(this._lastCallTime=d,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(h-f,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(d,f){super(d,f);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",h=>this._OnCreate(h)],["destroy",h=>this._OnDestroy(h)],["set-visible",h=>this._OnSetVisible(h)],["update-position",h=>this._OnUpdatePosition(h)],["update-state",h=>this._OnUpdateState(h)],["focus",h=>this._OnSetFocus(h)],["set-css-style",h=>this._OnSetCssStyle(h)],["set-attribute",h=>this._OnSetAttribute(h)],["remove-attribute",
h=>this._OnRemoveAttribute(h)]]);this.AddDOMElementMessageHandler("get-element",h=>h)}SetAutoAttach(d){this._autoAttach=!!d}AddDOMElementMessageHandler(d,f){this.AddRuntimeMessageHandler(d,h=>{const l=this._elementMap.get(h.elementId);return f(l,h)})}_OnCreate(d){const f=d.elementId,h=this.CreateElement(f,d);this._elementMap.set(f,h);h.style.boxSizing="border-box";d.isVisible||(h.style.display="none");d=this._GetFocusElement(h);d.addEventListener("focus",l=>this._OnFocus(f));d.addEventListener("blur",
l=>this._OnBlur(f));this._autoAttach&&document.body.appendChild(h)}CreateElement(d,f){throw Error("required override");}DestroyElement(d){}_OnDestroy(d){d=d.elementId;const f=this._elementMap.get(d);this.DestroyElement(f);this._autoAttach&&f.parentElement.removeChild(f);this._elementMap.delete(d)}PostToRuntimeElement(d,f,h){h||(h={});h.elementId=f;this.PostToRuntime(d,h)}_PostToRuntimeElementMaybeSync(d,f,h){h||(h={});h.elementId=f;this._PostToRuntimeMaybeSync(d,h)}_OnSetVisible(d){this._autoAttach&&
(this._elementMap.get(d.elementId).style.display=d.isVisible?"":"none")}_OnUpdatePosition(d){if(this._autoAttach){var f=this._elementMap.get(d.elementId);f.style.left=d.left+"px";f.style.top=d.top+"px";f.style.width=d.width+"px";f.style.height=d.height+"px";d=d.fontSize;null!==d&&(f.style.fontSize=d+"em")}}_OnUpdateState(d){const f=this._elementMap.get(d.elementId);this.UpdateState(f,d)}UpdateState(d,f){throw Error("required override");}_GetFocusElement(d){return d}_OnFocus(d){this.PostToRuntimeElement("elem-focused",
d)}_OnBlur(d){this.PostToRuntimeElement("elem-blurred",d)}_OnSetFocus(d){const f=this._GetFocusElement(this._elementMap.get(d.elementId));d.focus?f.focus():f.blur()}_OnSetCssStyle(d){this._elementMap.get(d.elementId).style[d.prop]=d.val}_OnSetAttribute(d){this._elementMap.get(d.elementId).setAttribute(d.name,d.val)}_OnRemoveAttribute(d){this._elementMap.get(d.elementId).removeAttribute(d.name)}GetElementById(d){return this._elementMap.get(d)}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),f=/android/i.test(navigator.userAgent);let h=0;function l(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.isStringSrc?new Promise(e=>{const g="c3_resolve_"+h;++h;self[g]=e;a.textContent=c.str+`\n\nself["${g}"]();`;document.head.appendChild(a)}):new Promise((e,g)=>{a.onload=e;a.onerror=g;a.src=c;document.head.appendChild(a)})}let m=!1,v=!1;function w(){if(!m){try{new Worker("blob://",{get type(){v=
!0}})}catch(c){}m=!0}return v}let u=new Audio;const x={"audio/webm; codecs=opus":!!u.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!u.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!u.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!u.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!u.canPlayType("audio/mp4"),"audio/mpeg":!!u.canPlayType("audio/mpeg")};u=null;async function H(c){c=await E(c);return(new TextDecoder("utf-8")).decode(c)}
function E(c){return new Promise((a,e)=>{const g=new FileReader;g.onload=k=>a(k.target.result);g.onerror=k=>e(k);g.readAsArrayBuffer(c)})}const y=[];let z=0;window.RealFile=window.File;const A=[],D=new Map,t=new Map;let F=0;const B=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");B.push(c)};const I=new Set(["cordova","playable-ad","instant-games"]);function G(c){return I.has(c)}let b=!1;window.RuntimeInterface=class c{constructor(a){this._useWorker=
a.useWorker;this._messageChannelPort=null;this._runtimeBaseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._canvas=this._runtimeDomHandler=null;this._isExportingToVideo=!1;this._exportToVideoDuration=0;this._jobScheduler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;this._isFileProtocol="file"===location.protocol.substr(0,4);!this._useWorker||"undefined"!==
typeof OffscreenCanvas&&navigator.userActivation&&w()||(this._useWorker=!1);if("playable-ad"===this._exportType||"instant-games"===this._exportType)this._useWorker=!1;if("cordova"===this._exportType&&this._useWorker)if(f){const e=/Chrome\/(\d+)/i.exec(navigator.userAgent);e&&90<=parseInt(e[1],10)||(this._useWorker=!1)}else this._useWorker=!1;this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||!this._isFileProtocol||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
"html5"!==this._exportType||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",e=>this._OnCordovaFetchLocalFile(e));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",e=>this._OnCreateJobWorker(e));"cordova"===this._exportType?document.addEventListener("deviceready",
()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetRuntimeBaseURL(){return this._runtimeBaseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsFileProtocol(){return this._isFileProtocol}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return d&&
"cordova"===this._exportType}IsiOSWebView(){const a=navigator.userAgent;return d&&G(this._exportType)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}IsAndroid(){return f}IsAndroidWebView(){return f&&G(this._exportType)}async _Init(a){"macos-wkwebview"===this._exportType&&this._SendWrapperMessage({type:"ready"});if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let g=0,k=a.engineScripts.length;g<
k;++g){var e=a.engineScripts[g].toLowerCase();this._localFileStrings.hasOwnProperty(e)?a.engineScripts[g]={isStringSrc:!0,str:this._localFileStrings[e]}:this._localFileBlobs.hasOwnProperty(e)&&(a.engineScripts[g]=URL.createObjectURL(this._localFileBlobs[e]))}}a.runtimeBaseUrl?this._runtimeBaseUrl=a.runtimeBaseUrl:(e=location.origin,this._runtimeBaseUrl=("null"===e?"file:///":e)+location.pathname,e=this._runtimeBaseUrl.lastIndexOf("/"),-1!==e&&(this._runtimeBaseUrl=this._runtimeBaseUrl.substr(0,e+
1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);e=new MessageChannel;this._messageChannelPort=e.port1;this._messageChannelPort.onmessage=g=>this._OnMessageFromRuntime(g.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(g=>this._OnMessageFromDebugger(g));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((g,
k)=>{window.AndroidFullScreen.immersiveMode(g,k)})}catch(g){console.error("Failed to enter Android immersive mode: ",g)}this._useWorker?await this._InitWorker(a,e.port2):await this._InitDOM(a,e.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:
a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,e,g){if(a.startsWith("blob:"))return new Worker(a,g);if("cordova"===this._exportType&&this._isFileProtocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(g.isC3MainWorker?a:this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),g);a=new URL(a,e);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
g)}return new Worker(a,g)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_GetCommonRuntimeOptions(a){return{runtimeBaseUrl:this._runtimeBaseUrl,previewUrl:location.href,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:c.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,
previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:(new URLSearchParams(self.location.search)).has("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isFileProtocol:this._isFileProtocol,
isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,e){var g=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(g,this._runtimeBaseUrl,{type:"module",name:"Runtime",isC3MainWorker:!0});this._canvas=document.createElement("canvas");this._canvas.style.display="none";g=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();let k=a.workerDependencyScripts||[],p=a.engineScripts;k=await Promise.all(k.map(n=>this._MaybeGetCordovaScriptURL(n)));p=await Promise.all(p.map(n=>this._MaybeGetCordovaScriptURL(n)));if("cordova"===this._exportType)for(let n=0,q=a.projectScripts.length;n<q;++n){const r=a.projectScripts[n],C=r[0];if(C===a.mainProjectScript||"scriptsInEvents.js"===C||C.endsWith("/scriptsInEvents.js"))r[1]=await this._MaybeGetCordovaScriptURL(C)}this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),
{type:"init-runtime",isInWorker:!0,messagePort:e,canvas:g,workerDependencyScripts:k,engineScripts:p,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,g,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=A.map(n=>new n(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(n,q)=>this._runtimeDomHandler._InvokeFunctionFromJS(n,q);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime",
"go-to-last-error-script"))}async _InitDOM(a,e){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this._domHandlers=A.map(n=>new n(this));this._FindRuntimeDOMHandler();var g=a.engineScripts.map(n=>"string"===typeof n?(new URL(n,this._runtimeBaseUrl)).toString():n);Array.isArray(a.workerDependencyScripts)&&g.unshift(...a.workerDependencyScripts);
g=await Promise.all(g.map(n=>this._MaybeGetCordovaScriptURL(n)));await Promise.all(g.map(n=>l(n)));g=self.C3_ProjectScriptsStatus;const k=a.mainProjectScript,p=a.projectScripts;for(let [n,q]of p)if(q||(q=n),n===k)try{q=await this._MaybeGetCordovaScriptURL(q),await l(q),"preview"!==this._exportType||g[n]||this._ReportProjectMainScriptError(n,"main script did not run to completion")}catch(r){this._ReportProjectMainScriptError(n,r)}else if("scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q=
await this._MaybeGetCordovaScriptURL(q),await l(q);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:e,canvas:this._canvas,runOnStartupFunctions:B}),
this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectMainScriptError(a,e){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,e);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=window.cr_previewLoadingElem;
a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,e,g,k,p){this._messageChannelPort.postMessage({type:"event",component:a,handler:e,dispatchOpts:k||null,data:g,responseId:null},p)}PostToRuntimeComponentAsync(a,e,g,k,p){const n=F++,q=new Promise((r,
C)=>{t.set(n,{resolve:r,reject:C})});this._messageChannelPort.postMessage({type:"event",component:a,handler:e,dispatchOpts:k||null,data:g,responseId:n},p);return q}["_OnMessageFromRuntime"](a){const e=a.type;if("event"===e)return this._OnEventFromRuntime(a);if("result"===e)this._OnResultFromRuntime(a);else if("runtime-ready"===e)this._OnRuntimeReady();else if("alert-error"===e)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===e)this._OnBeforeCreateRuntime();else throw Error(`unknown message '${e}'`);
}_OnEventFromRuntime(a){const e=a.component,g=a.handler,k=a.data,p=a.responseId;if(a=D.get(e))if(a=a.get(g)){var n=null;try{n=a(k)}catch(q){console.error(`Exception in '${e}' handler '${g}':`,q);null!==p&&this._PostResultToRuntime(p,!1,""+q);return}if(null===p)return n;n&&n.then?n.then(q=>this._PostResultToRuntime(p,!0,q)).catch(q=>{console.error(`Rejection from '${e}' handler '${g}':`,q);this._PostResultToRuntime(p,!1,""+q)}):this._PostResultToRuntime(p,!0,n)}else console.warn(`[DOM] No handler '${g}' for component '${e}'`);
else console.warn(`[DOM] No event handlers for component '${e}'`)}_PostResultToRuntime(a,e,g){let k;g&&g.transferables&&(k=g.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:e,result:g},k)}_OnResultFromRuntime(a){const e=a.responseId,g=a.isOk;a=a.result;const k=t.get(e);g?k.resolve(a):k.reject(a);t.delete(e)}AddRuntimeComponentMessageHandler(a,e,g){let k=D.get(a);k||(k=new Map,D.set(a,k));if(k.has(e))throw Error(`[DOM] Component '${a}' already has handler '${e}'`);
k.set(e,g)}static AddDOMHandlerClass(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||b)}static _SetWrapperIsFullscreenFlag(a){b=!!a}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&
this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!x[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}SetIsExportingToVideo(a){this._isExportingToVideo=!0;this._exportToVideoDuration=a}IsExportingToVideo(){return this._isExportingToVideo}GetExportToVideoDuration(){return this._exportToVideoDuration}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a){return"cordova"===
this._exportType&&(a.startsWith("file:")||this._isFileProtocol&&this.IsRelativeURL(a))?(a.startsWith(this._runtimeBaseUrl)&&(a=a.substr(this._runtimeBaseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),a=new Blob([a],{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const e=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(e);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(e);default:throw Error("unsupported type");
}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,e){a=a[e];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const e=this._GetPermissionAPI();return new Promise((g,k)=>e.checkPermission(this._MapPermissionID(e,a),p=>g(!!p.hasPermission),k))}_RequestPermission(a){const e=this._GetPermissionAPI();return new Promise((g,
k)=>e.requestPermission(this._MapPermissionID(e,a),p=>g(!!p.hasPermission),k))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const e of a)if(!await this._HasPermission(e)&&!1===await this._RequestPermission(e))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const e=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((g,
k)=>{window.resolveLocalFileSystemURL(e,p=>{p.file(g,k)},k)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await H(a)}_CordovaMaybeStartNextArrayBufferRead(){if(y.length&&!(8<=z)){z++;var a=y.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((e,g)=>{y.push({filename:a,successCallback:k=>{z--;this._CordovaMaybeStartNextArrayBufferRead();e(k)},errorCallback:k=>
{z--;this._CordovaMaybeStartNextArrayBufferRead();g(k)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,e,g){try{const k=await this.CordovaFetchLocalFile(a),p=await E(k);e(p)}catch(k){g(k)}}_SendWrapperMessage(a){if("windows-webview2"===this._exportType)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this._exportType)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");
}async _ConvertDataUrisToBlobs(){const a=[];for(const [e,g]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(e,g));await Promise.all(a)}async _ConvertDataUriToBlobs(a,e){if("object"===typeof e)this._localFileBlobs[a]=new Blob([e.str],{type:e.type}),this._localFileStrings[a]=e.str;else{let g=await this._FetchDataUri(e);g||(g=this._DataURIToBinaryBlobSync(e));this._localFileBlobs[a]=g}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
e),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var e=a.indexOf(",");if(0>e)throw new URIError("expected comma in data: uri");var g=a.substring(5,e);a=a.substring(e+1);e=g.split(";");g=e[0]||"";const k=e[2];a="base64"===e[1]||"base64"===k?atob(a):decodeURIComponent(a);return{mime_type:g,data:a}}_BinaryStringToBlob(a,e){var g=a.length;let k=g>>2,p=new Uint8Array(g),n=new Uint32Array(p.buffer,0,k),q,r;for(r=q=0;q<k;++q)n[q]=
a.charCodeAt(r++)|a.charCodeAt(r++)<<8|a.charCodeAt(r++)<<16|a.charCodeAt(r++)<<24;for(g&=3;g--;)p[r]=a.charCodeAt(r),++r;return new Blob([p],{type:e})}}}"use strict";
{const d=self.RuntimeInterface;function f(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const h=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),l={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},m={dispatchUserScriptEvent:!0},v={dispatchRuntimeEvent:!0};function w(b){return new Promise((c,a)=>{const e=document.createElement("link");e.onload=()=>c(e);e.onerror=
g=>a(g);e.rel="stylesheet";e.href=b;document.head.appendChild(e)})}function u(b){return new Promise((c,a)=>{const e=new Image;e.onload=()=>c(e);e.onerror=g=>a(g);e.src=b})}async function x(b){b=URL.createObjectURL(b);try{return await u(b)}finally{URL.revokeObjectURL(b)}}function H(b){return new Promise((c,a)=>{let e=new FileReader;e.onload=g=>c(g.target.result);e.onerror=g=>a(g);e.readAsText(b)})}async function E(b,c,a){if(!/firefox/i.test(navigator.userAgent))return await x(b);var e=await H(b);e=
(new DOMParser).parseFromString(e,"image/svg+xml");const g=e.documentElement;if(g.hasAttribute("width")&&g.hasAttribute("height")){const k=g.getAttribute("width"),p=g.getAttribute("height");if(!k.includes("%")&&!p.includes("%"))return await x(b)}g.setAttribute("width",c+"px");g.setAttribute("height",a+"px");e=(new XMLSerializer).serializeToString(e);b=new Blob([e],{type:"image/svg+xml"});return await x(b)}function y(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const z=new Set(["input","textarea","datalist","select"]);function A(b){return z.has(b.tagName.toLowerCase())||y(b)}const D=new Set(["canvas","body","html"]);function t(b){const c=b.target.tagName.toLowerCase();D.has(c)&&b.preventDefault()}function F(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await x(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";
document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(b,c,a,e,g){b=await E(b,c,a);const k=document.createElement("canvas");k.width=e;k.height=g;k.getContext("2d").drawImage(b,0,0,c,a);return k};let B=!1;document.addEventListener("pause",()=>B=!0);document.addEventListener("resume",()=>B=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function G(){const b=
document.activeElement;if(!b)return!1;const c=b.tagName.toLowerCase(),a=new Set("email number password search tel text url".split(" "));return"textarea"===c?!0:"input"===c?a.has(b.type.toLowerCase()||"text"):y(b)}d.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._debugHighlightElem=null;this._isExportToVideo=
!1;this._exportVideoProgressMessage="";this._exportVideoUpdateTimerId=-1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=null;this._pointerRawMovementY=this._pointerRawMovementX=0;this._enableAndroidVKDetection=!1;this._lastWindowWidth=b._GetWindowInnerWidth();this._lastWindowHeight=b._GetWindowInnerHeight();this._virtualKeyboardHeight=0;b.AddRuntimeComponentMessageHandler("canvas","update-size",e=>this._OnUpdateCanvasSize(e));b.AddRuntimeComponentMessageHandler("runtime","invoke-download",
e=>this._OnInvokeDownload(e));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",e=>this._OnRasterSvgImage(e));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",e=>this._OnGetSvgImageSize(e));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",e=>this._OnSetTargetOrientation(e));b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",e=>this._OnPostToDebugger(e));
b.AddRuntimeComponentMessageHandler("runtime","go-to-script",e=>this._OnPostToDebugger(e));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",e=>this._OnDebugHighlight(e));b.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());
b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",e=>this._OnAddStylesheet(e));b.AddRuntimeComponentMessageHandler("runtime","alert",e=>this._OnAlert(e));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());b.AddRuntimeComponentMessageHandler("runtime","set-exporting-to-video",e=>this._SetExportingToVideo(e));b.AddRuntimeComponentMessageHandler("runtime","export-to-video-progress",e=>this._OnExportVideoProgress(e));b.AddRuntimeComponentMessageHandler("runtime",
"exported-to-video",e=>this._OnExportedToVideo(e));const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",e=>{const g=e.target,k=g.tagName.toLowerCase();c.has(k)||y(g)||e.preventDefault()});const a=b.GetCanvas();window.addEventListener("selectstart",t);window.addEventListener("gesturehold",t);a.addEventListener("selectstart",t);a.addEventListener("gesturehold",t);window.addEventListener("touchstart",t,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
t,{passive:!1}),a.addEventListener("pointerdown",t)):a.addEventListener("touchstart",t);this._mousePointerLastButtons=0;window.addEventListener("mousedown",e=>{1===e.button&&e.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());
window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",e=>this._OnFullscreenError(e));window.addEventListener("webkitfullscreenerror",e=>this._OnFullscreenError(e));window.addEventListener("mozfullscreenerror",e=>this._OnFullscreenError(e));if(b.IsiOSWebView())if(window.visualViewport){let e=Infinity;window.visualViewport.addEventListener("resize",()=>{const g=window.visualViewport.height;g>e&&(document.scrollingElement.scrollTop=0);
e=g})}else window.addEventListener("focusout",()=>{G()||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=e=>this._OnWrapperMessage(e);this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){self.setTimeout(()=>{this._enableAndroidVKDetection=!0},1E3);"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):
document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!B)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:I()});this._mousePointerLastButtons=0});window.addEventListener("focusin",c=>{A(c.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",c=>this._OnKeyEvent("keydown",
c));window.addEventListener("keyup",c=>this._OnKeyEvent("keyup",c));window.addEventListener("dblclick",c=>this._OnMouseEvent("dblclick",c,l));window.addEventListener("wheel",c=>this._OnMouseWheelEvent("wheel",c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this._HandlePointerDownFocus(c);this._OnPointerEvent("pointerdown",c)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>
this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",c=>this._OnPointerRawUpdate(c))):window.addEventListener("pointermove",c=>this._OnPointerEvent("pointermove",c)),window.addEventListener("pointerup",c=>this._OnPointerEvent("pointerup",c)),window.addEventListener("pointercancel",c=>this._OnPointerEvent("pointercancel",c))):(window.addEventListener("mousedown",c=>{this._HandlePointerDownFocus(c);this._OnMouseEventAsPointer("pointerdown",
c)}),window.addEventListener("mousemove",c=>this._OnMouseEventAsPointer("pointermove",c)),window.addEventListener("mouseup",c=>this._OnMouseEventAsPointer("pointerup",c)),window.addEventListener("touchstart",c=>{this._HandlePointerDownFocus(c);this._OnTouchEvent("pointerdown",c)}),window.addEventListener("touchmove",c=>this._OnTouchEvent("pointermove",c)),window.addEventListener("touchend",c=>this._OnTouchEvent("pointerup",c)),window.addEventListener("touchcancel",c=>this._OnTouchEvent("pointercancel",
c)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this._iRuntime.IsAndroid()&&!this._iRuntime.IsAndroidWebView()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this._OnAndroidVirtualKeyboardChange(this._GetWindowInnerHeight(),
navigator.virtualKeyboard.boundingRect.height)}))}_OnAndroidVirtualKeyboardChange(b,c){document.body.style.transform="";if(0<c){var a=document.activeElement;a&&(a=a.getBoundingClientRect(),b=(a.top+a.bottom)/2-(b-c)/2,b>c&&(b=c),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`))}}_PostRuntimeEvent(b,c){this.PostToRuntime(b,c||null,v)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){if(!this._isExportToVideo){var b=
this._GetWindowInnerWidth(),c=this._GetWindowInnerHeight();if(this._iRuntime.IsAndroidWebView()){if(this._enableAndroidVKDetection){if(this._lastWindowWidth===b&&c<this._lastWindowHeight){this._virtualKeyboardHeight=this._lastWindowHeight-c;this._OnAndroidVirtualKeyboardChange(this._lastWindowHeight,this._virtualKeyboardHeight);return}0<this._virtualKeyboardHeight&&(this._virtualKeyboardHeight=0,this._OnAndroidVirtualKeyboardChange(c,this._virtualKeyboardHeight))}this._lastWindowWidth=b;this._lastWindowHeight=
c}this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,c,0))}}_ScheduleSimulatedResize(b,c,a){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(b,c,a),48)}_OnSimulatedResize(b,
c,a){const e=this._GetWindowInnerWidth(),g=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;e!=b||g!=c?this._PostRuntimeEvent("window-resize",{innerWidth:e,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.IsDocumentFullscreen()}):10>a&&this._ScheduleSimulatedResize(e,g,a+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>
console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}_OnFullscreenChange(){if(!this._isExportToVideo){var b=d.IsDocumentFullscreen();
b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",b);this.PostToRuntime("fullscreenerror",{isFullscreen:d.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():
this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,c){"Backspace"===c.key&&t(c);if(!this._isExportToVideo){var a=h.get(c.code)||c.code;this._PostToRuntimeMaybeSync(b,{code:a,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},l)}}_OnMouseWheelEvent(b,c){this._isExportToVideo||this.PostToRuntime(b,{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,
deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},l)}_OnMouseEvent(b,c,a){this._isExportToVideo||f(c)||this._PostToRuntimeMaybeSync(b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},a)}_OnMouseEventAsPointer(b,c){if(!this._isExportToVideo&&!f(c)){var a=this._mousePointerLastButtons;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==c.buttons&&
(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},l);this._mousePointerLastButtons=c.buttons;this._OnMouseEvent(c.type,c,m)}}_OnPointerEvent(b,c){if(!this._isExportToVideo){this._pointerRawUpdateRateLimiter&&"pointermove"!==
b&&this._pointerRawUpdateRateLimiter.Reset();var a=0;"mouse"===c.pointerType&&(a=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+this._pointerRawMovementX,movementY:(c.movementY||0)+this._pointerRawMovementY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||
0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},l);this._pointerRawMovementY=this._pointerRawMovementX=0;"mouse"===c.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this._OnMouseEvent(a,c,m),this._mousePointerLastButtons=c.buttons)}}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent&&(this._pointerRawMovementX+=this._lastPointerRawUpdateEvent.movementX||0,this._pointerRawMovementY+=this._lastPointerRawUpdateEvent.movementY||
0);this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,c){if(!this._isExportToVideo)for(let a=0,e=c.changedTouches.length;a<e;++a){const g=c.changedTouches[a];this._PostToRuntimeMaybeSync(b,{pointerId:g.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,
movementX:c.movementX||0,movementY:c.movementY||0,width:2*(g.radiusX||g.webkitRadiusX||0),height:2*(g.radiusY||g.webkitRadiusY||0),pressure:g.force||g.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:g.rotationAngle||0,timeStamp:c.timeStamp},l)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||
b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this._isExportToVideo||
this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},l)}_OnDeviceOrientationAbsolute(b){this._isExportToVideo||this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},l)}_OnDeviceMotion(b){if(!this._isExportToVideo){var c=null,a=b.acceleration;
a&&(c={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var e=b.accelerationIncludingGravity;e&&(a={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var g=b.rotationRate;g&&(e={alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0});this.PostToRuntime("devicemotion",{acceleration:c,accelerationIncludingGravity:a,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},l)}}_OnUpdateCanvasSize(b){var c=this.GetRuntimeInterface();c.IsExportingToVideo()||(c=c.GetCanvas(),c.style.width=b.styleWidth+"px",c.style.height=b.styleHeight+
"px",c.style.marginLeft=b.marginLeft+"px",c.style.marginTop=b.marginTop+"px",this._isFirstSizeUpdate&&(c.style.display="",this._isFirstSizeUpdate=!1))}_OnInvokeDownload(b){const c=b.url;b=b.filename;const a=document.createElement("a"),e=document.body;a.textContent=b;a.href=c;a.download=b;e.appendChild(a);a.click();e.removeChild(a)}async _OnRasterSvgImage(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,
c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await w(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const c of b)(b=c.play())&&b.catch(a=>{this._mediaRemovedPendingPlay.has(c)||this._mediaPendingPlay.add(c)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(b);
let c;try{c=b.play()}catch(a){this._mediaPendingPlay.add(b);return}c&&c.catch(a=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id=
"inspectOutline",document.body.appendChild(this._debugHighlightElem));var c=this._debugHighlightElem;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,
c){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:c})}_OnAlert(b){alert(b.message)}_OnWrapperMessage(b){"entered-fullscreen"===b?(d._SetWrapperIsFullscreenFlag(!0),this._OnFullscreenChange()):"exited-fullscreen"===b?(d._SetWrapperIsFullscreenFlag(!1),this._OnFullscreenChange()):console.warn("Unknown wrapper message: ",b)}_SetExportingToVideo(b){this._isExportToVideo=!0;const c=document.createElement("h1");c.id="exportToVideoMessage";c.textContent=b.message;document.body.prepend(c);
document.body.classList.add("exportingToVideo");this.GetRuntimeInterface().GetCanvas().style.display="";this._iRuntime.SetIsExportingToVideo(b.duration)}_OnExportVideoProgress(b){this._exportVideoProgressMessage=b.message;-1===this._exportVideoUpdateTimerId&&(this._exportVideoUpdateTimerId=setTimeout(()=>this._DoUpdateExportVideoProgressMessage(),250))}_DoUpdateExportVideoProgressMessage(){this._exportVideoUpdateTimerId=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=
this._exportVideoProgressMessage)}_OnExportedToVideo(b){window.c3_postToMessagePort({type:"exported-video",blob:b.blob,time:b.time})}})}"use strict";
self.JobSchedulerDOM=class{constructor(d){this._runtimeInterface=d;this._baseUrl=d.GetRuntimeBaseURL();"preview"===d.GetExportType()?this._baseUrl+="workers/":this._baseUrl+=d.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var d=this._runtimeInterface._GetWorkerURL("dispatchworker.js");
this._dispatchWorker=await this._runtimeInterface.CreateWorker(d,this._baseUrl,{name:"DispatchWorker"});d=new MessageChannel;this._inputPort=d.port1;this._dispatchWorker.postMessage({type:"_init","in-port":d.port2},[d.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const d=this._jobWorkers.length;var f=this._runtimeInterface._GetWorkerURL("jobworker.js");f=await this._runtimeInterface.CreateWorker(f,this._baseUrl,{name:"JobWorker"+d});const h=new MessageChannel,l=new MessageChannel;
this._dispatchWorker.postMessage({type:"_addJobWorker",port:h.port1},[h.port1]);f.postMessage({type:"init",number:d,"dispatch-port":h.port2,"output-port":l.port2},[h.port2,l.port2]);this._jobWorkers.push(f);return l.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
{function d(f){f.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(f){super(f,"button")}CreateElement(f,h){const l=document.createElement("input");var m=l;h.isCheckbox?(l.type="checkbox",m=document.createElement("label"),m.appendChild(l),m.appendChild(document.createTextNode("")),m.style.fontFamily="sans-serif",m.style.userSelect="none",m.style.webkitUserSelect="none",m.style.display="inline-block",m.style.color="black"):l.type="button";m.style.position=
"absolute";m.addEventListener("pointerdown",d);m.addEventListener("pointermove",d);m.addEventListener("pointerrawupdate",d);m.addEventListener("pointerup",d);m.addEventListener("mousedown",d);m.addEventListener("mouseup",d);m.addEventListener("keydown",d);m.addEventListener("keyup",d);l.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",f,{isChecked:l.checked}));h.id&&(l.id=h.id);h.className&&(l.className=h.className);this.UpdateState(m,h);return m}_GetInputElem(f){return"input"===
f.tagName.toLowerCase()?f:f.firstChild}_GetFocusElement(f){return this._GetInputElem(f)}UpdateState(f,h){const l=this._GetInputElem(f);l.checked=h.isChecked;l.disabled=!h.isEnabled;f.title=h.title;f===l?l.value=h.text:f.lastChild.textContent=h.text}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"touch");this.AddRuntimeMessageHandler("request-permission",f=>this._OnRequestPermission(f))}async _OnRequestPermission(d){d=d.type;let f=!0;0===d?f=await this._RequestOrientationPermission():1===d&&(f=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:d,result:f})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",f=>this._OnGetInitialState(f)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",f=>this._OnAlert(f)],["close",()=>this._OnClose()],["set-focus",f=>this._OnSetFocus(f)],["vibrate",f=>this._OnVibrate(f)],["lock-orientation",f=>this._OnLockOrientation(f)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",f=>this._OnNavigate(f)],["request-fullscreen",f=>this._OnRequestFullscreen(f)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",f=>this._OnSetHash(f)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton())}_OnGetInitialState(d){this._exportType=d.exportType;
return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(d=>this.PostToRuntime("sw-message",d.data))}_OnOnlineStateChanged(d){this.PostToRuntime("online-state",
{isOnline:d})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(d){alert(d.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(d){d=d.isFocus;if("nwjs"===this._exportType){const f=this.GetNWjsWindow();d?f.focus():f.blur()}else d?window.focus():window.blur()}_OnVibrate(d){navigator.vibrate&&
navigator.vibrate(d.pattern)}_OnLockOrientation(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(d):screen.webkitLockOrientation?f=screen.webkitLockOrientation(d):screen.mozLockOrientation?f=screen.mozLockOrientation(d):screen.msLockOrientation&&(f=screen.msLockOrientation(d));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",
f)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(d){}}_OnNavigate(d){var f=d.type;if("back"===f)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===f)window.history.forward();
else if("reload"===f)location.reload();else if("url"===f){f=d.url;const h=d.target;d=d.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):"preview"===d||"windows-webview2"===d?window.open(f,"_blank"):this._isConstructArcade||(2===h?window.top.location=f:1===h?window.parent.location=f:window.location=f)}else"new-window"===f&&(f=d.url,d=d.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):window.open(f,d))}_OnRequestFullscreen(d){if("windows-webview2"===
this._exportType||"macos-wkwebview"===this._exportType)self.RuntimeInterface._SetWrapperIsFullscreenFlag(!0),this._iRuntime._SendWrapperMessage({type:"set-fullscreen",fullscreen:!0});else{const f={navigationUI:"auto"};d=d.navUI;1===d?f.navigationUI="hide":2===d&&(f.navigationUI="show");d=document.documentElement;d.requestFullscreen?d.requestFullscreen(f):d.mozRequestFullScreen?d.mozRequestFullScreen(f):d.msRequestFullscreen?d.msRequestFullscreen(f):d.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?
d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):d.webkitRequestFullScreen())}}_OnExitFullscreen(){"windows-webview2"===this._exportType||"macos-wkwebview"===this._exportType?(self.RuntimeInterface._SetWrapperIsFullscreenFlag(!1),this._iRuntime._SendWrapperMessage({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&
document.webkitCancelFullScreen()}_OnSetHash(d){location.hash=d.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";
{function d(h){h.stopPropagation()}function f(h){13!==h.which&&27!==h.which&&h.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(h){super(h,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",l=>this._OnScrollToBottom(l))}CreateElement(h,l){let m;const v=l.type;"textarea"===v?(m=document.createElement("textarea"),m.style.resize="none"):(m=document.createElement("input"),m.type=v);m.style.position="absolute";m.autocomplete="off";
m.addEventListener("pointerdown",d);m.addEventListener("pointermove",d);m.addEventListener("pointerrawupdate",d);m.addEventListener("pointerup",d);m.addEventListener("mousedown",d);m.addEventListener("mouseup",d);m.addEventListener("keydown",f);m.addEventListener("keyup",f);m.addEventListener("click",w=>{w.stopPropagation();this._PostToRuntimeElementMaybeSync("click",h)});m.addEventListener("dblclick",w=>{w.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",h)});m.addEventListener("input",
()=>this.PostToRuntimeElement("change",h,{text:m.value}));l.id&&(m.id=l.id);l.className&&(m.className=l.className);this.UpdateState(m,l);return m}UpdateState(h,l){h.value=l.text;h.placeholder=l.placeholder;h.title=l.title;h.disabled=!l.isEnabled;h.readOnly=l.isReadOnly;h.spellcheck=l.spellCheck;l=l.maxLength;0>l?h.removeAttribute("maxlength"):h.setAttribute("maxlength",l)}_OnScrollToBottom(h){h.scrollTop=h.scrollHeight}})};
